/**
 * Round-trip through the REAL editor engine: original → Crepe (jsdom) → getMarkdown() → roundTrip().
 * This is the T-08/T-34 corpus check (IMPLEMENTATION-PLAN §2): every file in corpus/roundtrip must
 * come back byte-identical when nothing was edited.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { beforeAll, describe, expect, it } from 'vitest'
import { roundTrip } from '../src/roundtrip'
import { splitFrontMatter } from '../src/frontmatter'
import { createHeadlessEditor, type HeadlessEditor } from './helpers/headless-editor'

const corpusDir = resolve(__dirname, '../../../corpus/roundtrip')
const reportDir = resolve(__dirname, '../../../docs/perf')

function listCorpus(): string[] {
  try {
    return readdirSync(corpusDir)
      .filter((f) => f.endsWith('.md'))
      .sort()
  } catch {
    return []
  }
}

describe('Milkdown round-trip (corpus)', () => {
  let editor: HeadlessEditor

  beforeAll(async () => {
    editor = await createHeadlessEditor()
  })

  it('serializes a trivial document through Crepe', async () => {
    const md = await editor.roundTripMarkdown('# Hello\n\nworld\n')
    expect(md.trim()).toBe('# Hello\n\nworld')
  })

  it('keeps an unedited document byte-identical (sanity)', async () => {
    const original = '# T\n\nSome __strong__ and *em* text.\n\n* a\n* b\n'
    const current = await editor.roundTripMarkdown(splitFrontMatter(original).body)
    expect(roundTrip(original, current).text).toBe(original)
  })

  const files = listCorpus()
  const results: { file: string; ok: boolean; changed: number; blocks: number; note?: string }[] = []

  it.each(files)('%s', async (file) => {
    const raw = readFileSync(join(corpusDir, file), 'utf8').replace(/\r\n?/g, '\n')
    const { raw: fm, body } = splitFrontMatter(raw)
    let current: string
    try {
      current = await editor.roundTripMarkdown(body)
    } catch (err) {
      results.push({ file, ok: false, changed: -1, blocks: -1, note: `engine error: ${String(err)}` })
      throw err
    }
    const r = roundTrip(body, current)
    const out = fm + r.text
    const ok = out === raw
    results.push({ file, ok, changed: r.changedBlocks.length, blocks: body.split(/\n{2,}/).length })
    if (!ok) {
      mkdirSync(join(reportDir, 'roundtrip-diff'), { recursive: true })
      writeFileSync(join(reportDir, 'roundtrip-diff', file), out)
    }
    expect(ok, `${file}: ${r.changedBlocks.length} block(s) re-serialized`).toBe(true)
  })

  it('writes the corpus report', () => {
    if (files.length === 0) return
    const passed = results.filter((r) => r.ok).length
    const lines = [
      `# Round-trip corpus report`,
      ``,
      `Generated by test/milkdown-roundtrip.spec.ts on ${new Date().toISOString()}`,
      ``,
      `| Metric | Value |`,
      `|---|---|`,
      `| Files | ${results.length} |`,
      `| diff = 0 | ${passed} (${((passed / results.length) * 100).toFixed(1)}%) |`,
      ``,
      `| File | Result | Re-serialized blocks | Note |`,
      `|---|---|---|---|`,
      ...results.map((r) => `| ${r.file} | ${r.ok ? 'OK' : 'DIFF'} | ${r.changed} | ${r.note ?? ''} |`),
      ``,
    ]
    mkdirSync(reportDir, { recursive: true })
    writeFileSync(join(reportDir, 'roundtrip-report.md'), lines.join('\n'))
  })
})
